from typing import Iterator
from typing_extensions import Self
from os import PathLike
from datetime import datetime
import pathlib
from uuid import UUID
from enum import Enum, auto

from . import base, msa


class Installer(base.Installer):

    def __new__(cls, version: str | Version = Version.Release) -> Self: ...

    def __repr__(self) -> str: ...

    @base.Installer.version.getter
    def version(self) -> str | Version: ...
    @version.setter
    def version(self, version: str | Version): ...

    @property
    def fetch_excludes(self) -> list[FetchExclude]: ...
    @fetch_excludes.setter
    def fetch_excludes(self, excludes: list[FetchExclude]): ...

    def add_fetch_exclude(self, exclude: FetchExclude) -> None: ...
    def clear_fetch_exclude(self) -> None: ...

    @property
    def demo(self) -> bool: ...
    @demo.setter
    def demo(self, demo: bool): ...

    @property
    def quick_play(self) -> QuickPlay | None: ...
    @quick_play.setter
    def quick_play(self, quick_play: QuickPlay | None): ...

    @property
    def resolution(self) -> tuple[int, int] | None: ...
    @resolution.setter
    def resolution(self, resolution: tuple[int, int] | None): ...

    @property
    def disable_multiplayer(self) -> bool: ...
    @disable_multiplayer.setter
    def disable_multiplayer(self, disable_multiplayer: bool): ...

    @property
    def disable_chat(self) -> bool: ...
    @disable_chat.setter
    def disable_chat(self, disable_chat: bool): ...

    @property
    def auth_uuid(self) -> UUID: ...
    @property
    def auth_username(self) -> str: ...

    def set_auth_offline(self, uuid: UUID, username: str) -> None: ...
    def set_auth_offline_uuid(self, uuid: UUID) -> None: ...
    def set_auth_offline_username(self, username: str) -> None: ...
    def set_auth_offline_username_legacy(self, username: str) -> None: ...
    def set_auth_offline_hostname(self) -> None: ...
    def set_auth_msa(self, account: msa.Account) -> None: ...

    @property
    def client_id(self) -> str: ...
    @client_id.setter
    def client_id(self, client_id: str): ...

    @property
    def fix_legacy_quick_play(self) -> bool: ...
    @fix_legacy_quick_play.setter
    def fix_legacy_quick_play(self, fix: bool): ...

    @property
    def fix_legacy_proxy(self) -> bool: ...
    @fix_legacy_proxy.setter
    def fix_legacy_proxy(self, fix: bool): ...

    @property
    def fix_legacy_merge_sort(self) -> bool: ...
    @fix_legacy_merge_sort.setter
    def fix_legacy_merge_sort(self, fix: bool): ...

    @property
    def fix_legacy_resolution(self) -> bool: ...
    @fix_legacy_resolution.setter
    def fix_legacy_resolution(self, fix: bool): ...

    @property
    def fix_broken_authlib(self) -> bool: ...
    @fix_broken_authlib.setter
    def fix_broken_authlib(self, fix: bool): ...

    @property
    def fix_lwjgl(self) -> str | None: ...
    @fix_lwjgl.setter
    def fix_lwjgl(self, lwjgl_version: str | None): ...

    def install(self, handler: base.Handler | None = None) -> base.Game: ...


class Handler(base.Handler):

    def invalidated_version(self, version: str) -> None: ...
    def fetch_version(self, version: str) -> None: ...
    def fetched_version(self, version: str) -> None: ...
    def fixed_legacy_quick_play(self) -> None: ...
    def fixed_legacy_proxy(self, host: str, port: int) -> None: ...
    def fixed_legacy_merge_sort(self) -> None: ...
    def fixed_legacy_resolution(self) -> None: ...
    def fixed_broken_authlib(self) -> None: ...
    def warn_unsupported_quick_play(self) -> None: ...
    def warn_unsupported_resolution(self) -> None: ...


class Version(Enum):
    Release = auto()
    Snapshot = auto()


class QuickPlay:
    class Path(QuickPlay):
        path: pathlib.Path
        def __new__(cls, path: str | PathLike[str]) -> Self: ...
    class Singleplayer(QuickPlay):
        name: str
        def __new__(cls, name: str) -> Self: ...
    class Multiplayer(QuickPlay):
        host: str
        port: int
        def __new__(cls, host: str, port: int) -> Self: ...
    class Realms(QuickPlay):
        id: str
        def __new__(cls, id: str) -> Self: ...


class FetchExclude:
    class All(FetchExclude):
        """Exclude all versions from being fetched, it overrides all other excludes."""
        def __new__(cls) -> Self: ...
    class Exact(FetchExclude):
        name: str
        def __new__(cls, name: str) -> Self: ...
    class Regex(FetchExclude):
        pattern: str
        def __new__(cls, pattern: str) -> Self: ...


class Manifest:

    @staticmethod
    def request(handler: base.Handler | None = None) -> Manifest:
        """Request the Mojang versions manifest, the handler's `download_progress`
        method is called if the manifest needs to be downloaded."""

    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> ManifestVersion: ...
    def __iter__(self) -> Iterator[ManifestVersion]: ...

    @property
    def latest_release_name(self) -> str: ...
    @property
    def latest_snapshot_name(self) -> str: ...

    def find_by_name(self, name: str) -> ManifestVersion | None: ...


class ManifestVersion:

    def __repr__(self) -> str: ...

    @property
    def name(self) -> str: ...
    @property
    def channel(self) -> base.VersionChannel: ...
    @property
    def time(self) -> datetime: ...
    @property
    def release_time(self) -> datetime: ...
    @property
    def url(self) -> str: ...
    @property
    def size(self) -> int | None: ...
    @property
    def sha1(self) -> bytes | None: ...


class LwjglFixNotFoundError(base.Error):
    version: str
