from typing import Iterator
from typing_extensions import Self
from uuid import UUID
from os import PathLike
from pathlib import Path


class Auth:

    def __new__(cls, app_id: str) -> Self: ...

    def __repr__(self) -> str: ...

    @property
    def app_id(self) -> str: ...

    @property
    def language_code(self) -> str | None: ...
    @language_code.setter
    def language_code(self, code: str): ...

    def request_device_code(self) -> DeviceCodeFlow: ...


class DeviceCodeFlow:

    def __repr__(self) -> str: ...

    @property
    def app_id(self) -> str: ...
    @property
    def user_code(self) -> str: ...
    @property
    def verification_uri(self) -> str: ...
    @property
    def message(self) -> str: ...

    def wait(self) -> Account:
        """Wait for the user to authenticate, the GIL is released while waiting."""


class Account:

    def __repr__(self) -> str: ...

    @property
    def app_id(self) -> str: ...
    @property
    def access_token(self) -> str: ...
    @property
    def uuid(self) -> UUID: ...
    @property
    def username(self) -> str: ...
    @property
    def xuid(self) -> str: ...

    def request_profile(self) -> None: ...

    def request_refresh(self) -> None: ...


class Database:

    def __new__(cls, file: str | PathLike[str]) -> Self: ...

    def __repr__(self) -> str: ...

    @property
    def file(self) -> Path: ...

    def load_iter(self) -> Iterator[Account]: ...

    def load_from_uuid(self, uuid: UUID) -> Account | None: ...
    def load_from_username(self, username: str) -> Account | None: ...

    def remove_from_uuid(self, uuid: UUID) -> Account | None: ...
    def remove_from_username(self, username: str) -> Account | None: ...

    def store(self, account: Account) -> None: ...


class AuthError(Exception):
    """Base class for all authentication errors."""

class AuthDeclinedError(AuthError): ...

class AuthTimedOutError(AuthError): ...

class AuthOutdatedTokenError(AuthError):
    """The token is outdated when requesting the profile, it can be refreshed."""

class AuthDoesNotOwnGameError(AuthError): ...

class AuthInvalidStatusError(AuthError):
    status: int


class DatabaseError(Exception):
    """Base class for all account database errors, the cause is set to an `OSError`
    for I/O errors."""

class DatabaseCorruptedError(DatabaseError): ...

class DatabaseWriteFailedError(DatabaseError): ...
