[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "portablemc"
description = "Cross platform command line utility for launching Minecraft quickly and reliably with included support for Mojang versions and popular mod loaders."
readme = "../README.md"
license = "Apache-2.0"
authors = [{ name = "Théo Rozier", email = "contact@theorozier.fr" }]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/theorzr/portablemc"
Repository = "https://github.com/theorzr/portablemc"

[project.scripts]
portablemc = "portablemc._cli:main"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "portablemc._portablemc"
python-source = "python"
